# Generated by Django 3.2.4 on 2021-07-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_placeholder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeholder',
            name='cnfpass',
            field=models.CharField(default='Confirm Password', max_length=100),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='img',
            field=models.ImageField(default='C:/Users/vansh/Envs/test/project/login/static/images/image-1.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='img2',
            field=models.ImageField(default='C:/Users/vansh/Envs/test/project/login/static/images/image-2.png', upload_to='pics1'),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='mail',
            field=models.CharField(default='Mail_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='pas',
            field=models.CharField(default='Password', max_length=100),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='phno',
            field=models.CharField(default='PhoneNumber', max_length=100),
        ),
        migrations.AlterField(
            model_name='placeholder',
            name='user',
            field=models.CharField(default='Username', max_length=100),
        ),
    ]
